### ISSUE TITLE
Add edit button for users who opt in

### ISSUE THREAD

**Issue by boehs** [flancian/agora-server#28]
An addional yaml field that has a link to a way to edit content, such as it's location on github. Here is an example for mine:

```yaml
edit: https://github.com/boehs/oasis/blob/master/{path}.md
```

**Comment by flancian** [comment]
Nice idea!

1. In this case, would https://github.com/boehs/oasis/edit/master/CORS.md be perhaps a better choice? That is, /edit/ instead of blob -- which opens the editor directly.
2. I guess we could also autogenerate these, assuming regularity in github/gitlab/gitea URLs -- that could be a better choice? Then this parameter could become a way to override these defaults -- for example if you use a different interface/host, or if you want to redirect to (say) logseq/some other specialized web editor instead.

**Comment by boehs** [comment]
> 2. I guess we could also autogenerate these, assuming regularity in github/gitlab/gitea URLs -- that could be a better choice? Then this parameter could become a way to override these defaults -- for example if you use a different interface/host, or if you want to redirect to (say) logseq/some other specialized web editor instead.

I don't think so, ultimately your notes are your notes, it's great some people share their notes but they opt into that. letting people easily clone and modify the notes is probably a different step then just sharing.

Just me though, I feel pretty fine both ways

---

As for github edit links, cool! never knew that worked for other people to easily submit prs.
